### ISSUE TITLE
不用底線

### ISSUE THREAD

**Issue by dreambo4** [wayne900204/Java-MVVM-SQLiteOpenHelper#1]
我們的 coding style 沒有這種規則
https://github.com/wayne900204/Java-MVVM-SQLiteOpenHelper/blob/1169c9d719b3adeba040ddd12313c6650b3140eb/app/src/main/java/com/example/sqlmvvm/MainActivity.java#L73

**Comment by wayne900204** [comment]
已經移動到 ViewModel 裡面了。
